In [52]:
import pandas as pd
from sqlalchemy import create_engine
import glob
import os
import pyodbc
import pandas as pd
import sqlite3
import numpy as np

In [2]:
#!pip install pymysql

In [3]:
pd.option_context('display.max_rows', None)

In [4]:
path = r'/Users/dech/Documents/IS497DBA/Final-Project/Listings'                     # use your path
all_files = glob.glob(os.path.join(path, "*.csv"))

In [5]:
all_files

['/Users/dech/Documents/IS497DBA/Final-Project/Listings/listings (austin).csv',
 '/Users/dech/Documents/IS497DBA/Final-Project/Listings/listings (boston).csv',
 '/Users/dech/Documents/IS497DBA/Final-Project/Listings/listings(oakland).csv',
 '/Users/dech/Documents/IS497DBA/Final-Project/Listings/listings(new-orleans-la).csv',
 '/Users/dech/Documents/IS497DBA/Final-Project/Listings/listings (ashville).csv',
 '/Users/dech/Documents/IS497DBA/Final-Project/Listings/listings(twin-cities-msa).csv',
 '/Users/dech/Documents/IS497DBA/Final-Project/Listings/listings(san-mateo).csv',
 '/Users/dech/Documents/IS497DBA/Final-Project/Listings/listings (los-angeles).csv',
 '/Users/dech/Documents/IS497DBA/Final-Project/Listings/listings(jersey-city).csv',
 '/Users/dech/Documents/IS497DBA/Final-Project/Listings/listings (denver).csv',
 '/Users/dech/Documents/IS497DBA/Final-Project/Listings/listings (clark-county-nv).csv',
 '/Users/dech/Documents/IS497DBA/Final-Project/Listings/listings(new-york).csv',
 '/Users/dech/Documents/IS497DBA/Final-Project/Listings/listings(newark).csv',
 '/Users/dech/Documents/IS497DBA/Final-Project/Listings/listings (colombus).csv',
 '/Users/dech/Documents/IS497DBA/Final-Project/Listings/listings (santa-clara-county).csv',
 '/Users/dech/Documents/IS497DBA/Final-Project/Listings/listings(santa-cruz).csv',
 '/Users/dech/Documents/IS497DBA/Final-Project/Listings/listings(rhode-island).csv',
 '/Users/dech/Documents/IS497DBA/Final-Project/Listings/listings (washington-dc).csv',
 '/Users/dech/Documents/IS497DBA/Final-Project/Listings/listings(greater-manchester).csv',
 '/Users/dech/Documents/IS497DBA/Final-Project/Listings/listings(seattle).csv',
 '/Users/dech/Documents/IS497DBA/Final-Project/Listings/listings (new-orleans).csv',
 '/Users/dech/Documents/IS497DBA/Final-Project/Listings/listings(san-deigo).csv',
 '/Users/dech/Documents/IS497DBA/Final-Project/Listings/listings (hawaii).csv',
 '/Users/dech/Documents/IS497DBA/Final-Project/Listings/listings (broward-county).csv',
 '/Users/dech/Documents/IS497DBA/Final-Project/Listings/listings(portland-oregon).csv',
 '/Users/dech/Documents/IS497DBA/Final-Project/Listings/listings (nashville).csv',
 '/Users/dech/Documents/IS497DBA/Final-Project/Listings/listings (chicago).csv',
 '/Users/dech/Documents/IS497DBA/Final-Project/Listings/listings(salem-oregon).csv',
 '/Users/dech/Documents/IS497DBA/Final-Project/Listings/listings (san-francisco).csv',
 '/Users/dech/Documents/IS497DBA/Final-Project/Listings/listings(pacififc-grove).csv',
 '/Users/dech/Documents/IS497DBA/Final-Project/Listings/listings (cambridge).csv']

In [6]:
li = []

for filename in all_files:
    df = pd.read_csv(filename, index_col=None, header=0)
    li.append(df)

listing = pd.concat(li, axis=0, ignore_index=True)
pd.set_option('display.max_columns', None)

/Users/dech/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3437: DtypeWarning: Columns (67) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

In [7]:
listing.rename(index=str,columns={"name":"listing_name"},inplace=True)
listing.head()

,id,listing_url,scrape_id,last_scraped,listing_name,description,neighborhood_overview,picture_url,host_id,host_url,host_name,host_since,host_location,host_about,host_response_time,host_response_rate,host_acceptance_rate,host_is_superhost,host_thumbnail_url,host_picture_url,host_neighbourhood,host_listings_count,host_total_listings_count,host_verifications,host_has_profile_pic,host_identity_verified,neighbourhood,neighbourhood_cleansed,neighbourhood_group_cleansed,latitude,longitude,property_type,room_type,accommodates,bathrooms,bathrooms_text,bedrooms,beds,amenities,price,minimum_nights,maximum_nights,minimum_minimum_nights,maximum_minimum_nights,minimum_maximum_nights,maximum_maximum_nights,minimum_nights_avg_ntm,maximum_nights_avg_ntm,calendar_updated,has_availability,availability_30,availability_60,availability_90,availability_365,calendar_last_scraped,number_of_reviews,number_of_reviews_ltm,number_of_reviews_l30d,first_review,last_review,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,1078,https://www.airbnb.com/rooms/1078,20211211051409,2021-12-11,*UT/Hyde Park Craftsman Apartment,This upstairs apartment is surrounded by trees...,"Hyde Park is close to downtown, UT, 6th street...",https://a0.muscache.com/pictures/52472f12-2e2e...,4635658,https://www.airbnb.com/users/show/4635658,Tracy,2013-01-08,"Austin, Texas, United States",I have been a super-host for about 10 years an...,within an hour,100%,100%,t,https://a0.muscache.com/im/users/4635658/profi...,https://a0.muscache.com/im/users/4635658/profi...,University of Texas,2.0,2.0,"['email', 'phone', 'reviews', 'offline_governm...",t,t,"Austin, Texas, United States",78705,NaN,30.30002,-97.73637,Entire guesthouse,Entire home/apt,2,NaN,1 bath,1.0,1.0,"[""Microwave"", ""Shampoo"", ""Long term stays allo...",$102.00,1,365,1.0,1.0,1125.0,1125.0,1.0,1125.0,NaN,t,0,0,0,0,2021-12-11,232,5,2,2008-09-13,2021-11-21,4.89,4.92,4.83,4.93,4.91,4.87,4.87,NaN,t,2,2,0,0,1.44
1,2265,https://www.airbnb.com/rooms/2265,20211211051409,2021-12-11,Zen-East in the Heart of Austin (monthly rental),Zen East is situated in a vibrant & diverse mu...,NaN,https://a0.muscache.com/pictures/4187/52d4f5d0...,2466,https://www.airbnb.com/users/show/2466,Paddy,2008-08-23,"Austin, Texas, United States",I am a long time resident of Austin. I earned ...,within a day,100%,70%,t,https://a0.muscache.com/im/users/2466/profile_...,https://a0.muscache.com/im/users/2466/profile_...,East Downtown,3.0,3.0,"['email', 'phone', 'facebook', 'reviews', 'kba']",t,t,NaN,78702,NaN,30.27752,-97.71377,Entire residential home,Entire home/apt,4,NaN,2 baths,2.0,2.0,"[""Microwave"", ""Paid parking off premises"", ""Cl...",$179.00,7,180,7.0,7.0,180.0,180.0,7.0,180.0,NaN,t,0,0,0,0,2021-12-11,26,2,0,2009-03-17,2021-07-02,4.68,4.74,4.83,4.77,4.83,4.26,4.35,NaN,f,3,2,1,0,0.17
2,5245,https://www.airbnb.com/rooms/5245,20211211051409,2021-12-11,"Eco friendly, Colorful, Clean, Cozy monthly share",Situated in a vibrant & diverse multicultural ...,NaN,https://a0.muscache.com/pictures/5167505/b33b5...,2466,https://www.airbnb.com/users/show/2466,Paddy,2008-08-23,"Austin, Texas, United States",I am a long time resident of Austin. I earned ...,within a day,100%,70%,t,https://a0.muscache.com/im/users/2466/profile_...,https://a0.muscache.com/im/users/2466/profile_...,East Downtown,3.0,3.0,"['email', 'phone', 'facebook', 'reviews', 'kba']",t,t,NaN,78702,NaN,30.27614,-97.71320,Private room in residential home,Private room,2,NaN,1 private bath,1.0,2.0,"[""TV with standard cable"", ""Shampoo"", ""Long te...",$114.00,30,90,30.0,30.0,90.0,90.0,30.0,90.0,NaN,t,0,0,0,0,2021-12-11,9,0,0,2009-03-19,2018-03-14,4.57,4.80,4.20,5.00,4.40,4.75,4.50,NaN,f,3,2,1,0,0.06
3,5456,https://www.airbnb.com/rooms/5456,20211211051409,2021-12-11,"Walk to 6th, Rainey St and Convention Ctr",Great central location for walking to Convent...,My neighborhood is ideally located if you want...,https://a0.muscache.com/pictures/14084884/b5a3...,8028,https://www.airbnb.com/users/show/8028,Sylvia,2009-02-16,"Austin, Texas, United States",I am a licensed Real Estate Broker and owner o...,within a few hours,100%,94%,t,https://a0.muscache.com/im/users/8028/profile_...,https://a0.muscache.com/im/users/8028/profile_...,East Downtown,1.0,1.0,"['email', 'phone', 'reviews', 'kba']",t,t,"Austin, Texas, United States",78702,NaN,30.26057,-97.73441,Entire guesthouse,Entire home/apt,3,NaN,1 bath,1.0,2.0,"[""Microwave"", ""Shampoo"", ""Long term stays allo...",$104.00,2,90,2.0,2.0,90.0,90.0,2.0,90.0,NaN,t,26,56,80,345,2021-12-11,578,40,1,2009-03-08,2021-11-18,4.83,4.87,4.84,4.89,4.80,4.73,4.78,NaN,f,1,1,0,0,3.72
4,5769,https://www.airbnb.com/rooms/5769,20211211051409,2021-12-11,NW Austin Room,<b>The space</b><br />Looking for a comfortabl...,Quiet neighborhood with lots of trees and good...,https://a0.muscache.com/pictures/23822033/ac94...,8186,https://www.airbnb.com/users/show/8186,Elizabeth,2009-02-19,"Austin, Texas, United States",We're easygoing professionals that enjoy meeti...,NaN,NaN,100%,t,https://a0.muscache.com/im/users/8186/profile_...,https://a0.muscache.com/im/users/8186/profile_...,SW Williamson Co.,1.0,1.0,"['email', 'phone', 'reviews', 'jumio', 'govern...",t,t,"Austin, Texas, United States",78729,NaN,30.45697,-97.78422,Private room in residential home,Private room,2,NaN,1 shared bath,1.0,1.0,"[""TV with standard cable"", ""Shampoo"", ""Free pa...",$39.00,1,14,1.0,1.0,14.0,14.0,1.0,14.0,NaN,t,0,0,0,0,2021-12-11,264,6,0,2010-04-10,2021-07-03,4.90,4.90,4.86,4.91,4.94,4.74,4.92,NaN,f,1,0,1,0,1.86

In [8]:
with pd.option_context('display.max_rows', None, 'display.max_columns', None):
    print(listing.dtypes)

id                                                int64
listing_url                                      object
scrape_id                                         int64
last_scraped                                     object
listing_name                                     object
description                                      object
neighborhood_overview                            object
picture_url                                      object
host_id                                           int64
host_url                                         object
host_name                                        object
host_since                                       object
host_location                                    object
host_about                                       object
host_response_time                               object
host_response_rate                               object
host_acceptance_rate                             object
host_is_superhost                                object
host_thumbnail_url                               object
host_picture_url                                 object
host_neighbourhood                               object
host_listings_count                             float64
host_total_listings_count                       float64
host_verifications                               object
host_has_profile_pic                             object
host_identity_verified                           object
neighbourhood                                    object
neighbourhood_cleansed                           object
neighbourhood_group_cleansed                     object
latitude                                        float64
longitude                                       float64
property_type                                    object
room_type                                        object
accommodates                                      int64
bathrooms                                       float64
bathrooms_text                                   object
bedrooms                                        float64
beds                                            float64
amenities                                        object
price                                            object
minimum_nights                                    int64
maximum_nights                                    int64
minimum_minimum_nights                          float64
maximum_minimum_nights                          float64
minimum_maximum_nights                          float64
maximum_maximum_nights                          float64
minimum_nights_avg_ntm                          float64
maximum_nights_avg_ntm                          float64
calendar_updated                                float64
has_availability                                 object
availability_30                                   int64
availability_60                                   int64
availability_90                                   int64
availability_365                                  int64
calendar_last_scraped                            object
number_of_reviews                                 int64
number_of_reviews_ltm                             int64
number_of_reviews_l30d                            int64
first_review                                     object
last_review                                      object
review_scores_rating                            float64
review_scores_accuracy                          float64
review_scores_cleanliness                       float64
review_scores_checkin                           float64
review_scores_communication                     float64
review_scores_location                          float64
review_scores_value                             float64
license                                          object
instant_bookable                                 object
calculated_host_listings_count                    int64
calculated_host_listings_count_entire_homes       int64
calculated_host_listings_count_private_rooms      int64
calculated_host_listings_count_shared_rooms       int64
reviews_per_month                               float64
dtype: object

In [9]:
listing_df = listing[["id","listing_name","neighbourhood_cleansed",
                      "neighbourhood_group_cleansed","latitude","longitude",
                      "property_type","room_type",
                      "accommodates","bathrooms","bedrooms","beds","price",
                      "minimum_nights","maximum_nights","minimum_nights_avg_ntm","maximum_nights_avg_ntm",
                       "has_availability",
                      "availability_30","availability_60","availability_90","availability_365",
                      "number_of_reviews","first_review", "last_review",
                      "review_scores_rating","review_scores_accuracy","review_scores_cleanliness",
                      "review_scores_checkin","review_scores_communication","review_scores_location",
                      "review_scores_value","instant_bookable","reviews_per_month"]].copy()

In [10]:
listing_df = listing_df.fillna(0)

In [11]:
# convert dates to datetime
listing_df["first_review"]=pd.to_datetime(listing_df["first_review"])
listing_df["last_review"]=pd.to_datetime(listing_df["last_review"])

In [12]:
# convert boolean columns to boolean

listing_df["instant_bookable"].replace(["t","f"],[True,False],inplace=True)
listing_df["has_availability"].replace(["t","f"],[True,False],inplace=True)

In [13]:
listing_df['price'] = listing_df['price'].replace({'\$': '', ',': ''}, regex=True)

In [14]:
listing_df["price"] = pd.to_numeric(listing_df["price"])

In [15]:
with pd.option_context('display.max_rows', None, 'display.max_columns', None):
    print(listing_df.dtypes)

id                                       int64
listing_name                            object
neighbourhood_cleansed                  object
neighbourhood_group_cleansed            object
latitude                               float64
longitude                              float64
property_type                           object
room_type                               object
accommodates                             int64
bathrooms                              float64
bedrooms                               float64
beds                                   float64
price                                  float64
minimum_nights                           int64
maximum_nights                           int64
minimum_nights_avg_ntm                 float64
maximum_nights_avg_ntm                 float64
has_availability                          bool
availability_30                          int64
availability_60                          int64
availability_90                          int64
availability_365                         int64
number_of_reviews                        int64
first_review                    datetime64[ns]
last_review                     datetime64[ns]
review_scores_rating                   float64
review_scores_accuracy                 float64
review_scores_cleanliness              float64
review_scores_checkin                  float64
review_scores_communication            float64
review_scores_location                 float64
review_scores_value                    float64
instant_bookable                          bool
reviews_per_month                      float64
dtype: object

In [16]:
listing_df.to_csv("listing.csv",index=False)

In [17]:
listing_df.sample(6)

,id,listing_name,neighbourhood_cleansed,neighbourhood_group_cleansed,latitude,longitude,property_type,room_type,accommodates,bathrooms,bedrooms,beds,price,minimum_nights,maximum_nights,minimum_nights_avg_ntm,maximum_nights_avg_ntm,has_availability,availability_30,availability_60,availability_90,availability_365,number_of_reviews,first_review,last_review,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,instant_bookable,reviews_per_month
63189,52848692,Spacious Luxury Guest Studio w/Queen Bed Long ...,West Hills,City of Los Angeles,34.19201,-118.64767,Entire guest suite,Entire home/apt,2,0.0,0.0,1.0,153.0,31,100,31.0,1125.0,True,0,14,44,134,0,1970-01-01,1970-01-01,0.00,0.00,0.00,0.00,0.00,0.00,0.00,True,0.00
77964,49629644,"Cozy & Gated 4B/3B house, 1B/1B downstairs!!!",Unincorporated Areas,0,36.00504,-115.26535,Entire residential home,Entire home/apt,9,0.0,4.0,4.0,140.0,31,1125,31.0,1125.0,True,30,31,39,144,13,2021-05-10,2021-12-15,4.77,4.92,4.92,5.00,5.00,4.62,4.85,True,1.75
159628,32807819,Room 4: Private room/Shared Bath,San Ysidro,0,32.54359,-117.05303,Private room in residential home,Private room,2,0.0,1.0,1.0,49.0,2,29,2.0,29.0,True,16,46,76,166,48,2019-03-19,2021-12-19,4.74,4.85,4.55,4.96,4.87,4.81,4.72,False,1.43
62189,52373318,"Comfy & Spacious New 3 Bd. 2 Ba., Welcome ALL",Manchester Square,City of Los Angeles,33.96569,-118.30160,Entire residential home,Entire home/apt,8,0.0,3.0,5.0,240.0,2,1125,2.0,1125.0,True,5,19,49,323,1,2021-12-05,2021-12-05,5.00,5.00,5.00,5.00,5.00,4.00,5.00,False,1.00
135655,18652866,Private & Clean 1BR | Work Remote | Foggy Bottom,"West End, Foggy Bottom, GWU",0,38.90047,-77.05078,Entire rental unit,Entire home/apt,3,0.0,1.0,2.0,129.0,15,1125,15.0,1125.0,True,14,44,74,74,4,2017-08-26,2020-06-03,4.50,4.75,4.50,4.75,4.50,5.00,4.50,False,0.08
122605,52970021,ENTIRE PLACE | Top Floor Lux Space| Short North,Near North/University,0,39.98702,-83.00353,Entire rental unit,Entire home/apt,2,0.0,1.0,1.0,95.0,3,25,3.0,25.0,True,30,60,90,364,0,1970-01-01,1970-01-01,0.00,0.00,0.00,0.00,0.00,0.00,0.00,True,0.00

In [18]:
hosts = listing[["host_id","host_name",
                 "host_since","host_location",
                 "host_total_listings_count","host_neighbourhood","id"]]

In [19]:
hosts = hosts.fillna(0)

In [20]:
hosts.sample(10)

,host_id,host_name,host_since,host_location,host_total_listings_count,host_neighbourhood,id
150662,4539515,Bill,2012-12-31,"New Orleans, Louisiana, United States",2.0,Fairgrounds,17701413
10921,368944610,Carolyn,2020-09-23,"Houston, Texas, United States",2232.0,Cherry Creek,53021098
11196,359036978,Casey,2020-07-28,"Houston, Texas, United States",411.0,Bouldin Creek,53493312
118975,19303369,Hiroki,2014-08-01,"Queens, New York, United States",170.0,Elmhurst,53098339
126461,214899712,Stella,2018-09-11,"San Jose, California, United States",4.0,North San Jose,47786437
52848,79657632,Terry,2016-06-24,"Santa Monica, California, United States",1.0,Pico,43341995
139557,44113859,Keely,2015-09-13,"Washington, District of Columbia, United States",0.0,Deanwood,48298350
71944,100238132,Michael,2016-10-18,US,221.0,Kailua/Kona,21513553
191304,120722337,Shirley & Charles,2017-03-14,"Miramar, Florida, United States",1.0,0,17855323
33791,20651612,Venice Bungalow,2014-08-28,"Los Angeles, California, United States",1.0,0,3986484

In [21]:
# convert dates to datetime format
hosts["host_since"] = pd.to_datetime(hosts["host_since"])

In [22]:
hosts.drop_duplicates(keep="first",inplace=True)

In [23]:
hosts.dtypes

host_id                               int64
host_name                            object
host_since                   datetime64[ns]
host_location                        object
host_total_listings_count           float64
host_neighbourhood                   object
id                                    int64
dtype: object

In [24]:

hosts.to_csv("hosts.csv",index=False)

In [25]:
#df = pd.read_sql('SELECT * FROM hosts', con=db_connection)

In [26]:
# conn = pyodbc.connect(driver='{ODBC Driver 17 for SQL Server}',
#        server='airbnbserver.database.windows.net',
#        database='airbnb',
#        uid='airbnbadmin', pwd='Airbnb@123')

In [33]:
path = r'/Users/dech/Documents/IS497DBA/Final-Project/Reviews1'                     # use your path
all_ = glob.glob(os.path.join(path, "*.csv"))

In [34]:
all_

['/Users/dech/Documents/IS497DBA/Final-Project/Reviews1/reviews 3.csv',
 '/Users/dech/Documents/IS497DBA/Final-Project/Reviews1/reviews 2.csv',
 '/Users/dech/Documents/IS497DBA/Final-Project/Reviews1/reviews.csv',
 '/Users/dech/Documents/IS497DBA/Final-Project/Reviews1/reviews 6.csv',
 '/Users/dech/Documents/IS497DBA/Final-Project/Reviews1/reviews 7.csv',
 '/Users/dech/Documents/IS497DBA/Final-Project/Reviews1/reviews 5.csv',
 '/Users/dech/Documents/IS497DBA/Final-Project/Reviews1/reviews 4.csv',
 '/Users/dech/Documents/IS497DBA/Final-Project/Reviews1/reviews 27.csv',
 '/Users/dech/Documents/IS497DBA/Final-Project/Reviews1/reviews 26.csv',
 '/Users/dech/Documents/IS497DBA/Final-Project/Reviews1/reviews 18.csv',
 '/Users/dech/Documents/IS497DBA/Final-Project/Reviews1/reviews 24.csv',
 '/Users/dech/Documents/IS497DBA/Final-Project/Reviews1/reviews 25.csv',
 '/Users/dech/Documents/IS497DBA/Final-Project/Reviews1/reviews 19.csv',
 '/Users/dech/Documents/IS497DBA/Final-Project/Reviews1/reviews 21.csv',
 '/Users/dech/Documents/IS497DBA/Final-Project/Reviews1/reviews 20.csv',
 '/Users/dech/Documents/IS497DBA/Final-Project/Reviews1/reviews 22.csv',
 '/Users/dech/Documents/IS497DBA/Final-Project/Reviews1/reviews 23.csv',
 '/Users/dech/Documents/IS497DBA/Final-Project/Reviews1/reviews 12.csv',
 '/Users/dech/Documents/IS497DBA/Final-Project/Reviews1/reviews 13.csv',
 '/Users/dech/Documents/IS497DBA/Final-Project/Reviews1/reviews 11.csv',
 '/Users/dech/Documents/IS497DBA/Final-Project/Reviews1/reviews 10.csv',
 '/Users/dech/Documents/IS497DBA/Final-Project/Reviews1/reviews 14.csv',
 '/Users/dech/Documents/IS497DBA/Final-Project/Reviews1/reviews 28.csv',
 '/Users/dech/Documents/IS497DBA/Final-Project/Reviews1/reviews 29.csv',
 '/Users/dech/Documents/IS497DBA/Final-Project/Reviews1/reviews 15.csv',
 '/Users/dech/Documents/IS497DBA/Final-Project/Reviews1/reviews 17.csv',
 '/Users/dech/Documents/IS497DBA/Final-Project/Reviews1/reviews 16.csv',
 '/Users/dech/Documents/IS497DBA/Final-Project/Reviews1/reviews 9.csv',
 '/Users/dech/Documents/IS497DBA/Final-Project/Reviews1/reviews 8.csv']

In [41]:
rev = []

for filename in all_:
    df_reviews = pd.read_csv(filename, index_col=None, header=0)
    rev.append(df_reviews)

reviews = pd.concat(rev, axis=0, ignore_index=True)
pd.set_option('display.max_columns', None)

In [42]:
reviews.head()

,listing_id,id,date,reviewer_id,reviewer_name,comments
0,3781,37776825,2015-07-10,36059247,Greg,The apartment was as advertised and Frank was ...
1,3781,41842494,2015-08-09,10459388,Tai,It was a pleasure to stay at Frank's place. Th...
2,3781,45282151,2015-09-01,12264652,Damien,The apartment description is entirely faithful...
3,3781,49022647,2015-09-30,41426327,Mike,Thoroughly enjoyed my time at Frank's home. Ha...
4,3781,52503327,2015-10-30,15151513,Ivan,Great value for the money! This location has e...

In [44]:
# change column "date/id" to something that SQL doesn't already recognize
reviews.rename(index=str,columns={"date":"review_date"},inplace=True)
reviews.rename(columns={"id":"review_id"}, inplace=True)

In [47]:
reviews = reviews[['review_id', "listing_id", "review_date", "reviewer_id", "reviewer_name"]].copy()

In [61]:
type(reviews['listing_id'][0]) == np.int64

True

In [64]:
reviews.shape

(8249602, 5)

In [62]:
def check_numeric(x):
    
    bool_check = []
    for val in x: 
        bool_check.append(type(val) == np.int64) 
        
    return sum(bool_check)
    
true_false = check_numeric(reviews['listing_id'].values)

In [63]:
true_false

8249602

In [67]:
reviews['review_date'] = pd.to_datetime(reviews['review_date'])

In [69]:
reviews.info()

<class 'pandas.core.frame.DataFrame'>
Index: 8249602 entries, 0 to 8249601
Data columns (total 5 columns):
 #   Column         Dtype
---  ------         -----
 0   review_id      int64
 1   listing_id     int64
 2   review_date    datetime64[ns]
 3   reviewer_id    int64
 4   reviewer_name  object
dtypes: datetime64[ns](1), int64(3), object(1)
memory usage: 635.6+ MB

In [70]:
reviews.to_csv("reviews.csv",index=False)